# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: CustomMenu

# Model Form Field configuration
form: $/xitara/nexus/models/custommenu/fields.yaml

# Model Class name
modelClass: Xitara\Nexus\Models\CustomMenu

# Default redirect location
defaultRedirect: xitara/nexus/custommenus

# Create page
create:
    title: Create CustomMenu
    redirect: xitara/nexus/custommenus/update/:id
    redirectClose: xitara/nexus/custommenus

# Update page
update:
    title: Edit CustomMenu
    redirect: xitara/nexus/custommenus
    redirectClose: xitara/nexus/custommenus

# Preview page
preview:
    title: Preview CustomMenu
